### ISSUE TITLE
output lot of NewSelectionBox object when dragging

### ISSUE THREAD

**Issue by canGeEr** [AirLabsTeam/react-drag-to-select#10]
output lot of NewSelectionBox object when dragging

**Comment by chandlervdw** [comment]
+1 these are `console.log`s from the `dist` build

**Comment by dwilt** [comment]
@chandlervdw yea, let me take a look

**Comment by dwilt** [comment]
@chandlervdw @canGeEr you are using an older version of this package. Please uninstall `react-drag-to-select` and install `@air/react-drag-to-select` as per the docs. That should fix your problem!

**Comment by chandlervdw** [comment]
@dwilt Thanks. Unfortunately, adding the library via `@air/react-drag-to-select` has 2 issues:
1. I can no longer import `UseSelectionContainerParams` (your example imported it from `react-drag-to-select/dist/hooks/useSelectionContainer`. Appending `@air/` to the front of that import location doesn't work).
2. Even after `yarn clean && yarn install`, I get the following error when trying to run my project: 
```
Can't resolve 'react-style-object-to-css' in 'node_modules/@air/react-drag-to-select/dist'
```
You should ensure that you're export that type from `useSelectionContainer.tsx` and maybe update your README to reflect that installing `react-style-object-to-css` is required, too.

Thanks for the helpful library!
