### ISSUE TITLE
Selecting Doesn't work if the elements is in a scrollable parent

### ISSUE THREAD

**Issue by AhmedMustafa2201** [AirLabsTeam/react-drag-to-select#12]
- open the web page [react-drag-to-select documentation](https://airlabsteam.github.io/react-drag-to-select/)
- scroll to the bottom of the page
- select from bottom-to-top and select select the first 2 rows from the bottom

result:
- it selects the third row accidentally

please find this image as a guide for the issue

![image](https://user-images.githubusercontent.com/59970699/174753030-065c8a1c-6588-42d1-9b38-bdfed4db1620.png)

**Comment by dwilt** [comment]
@AhmedMustafa2201 ah, yes I've repro'd this when the page scrolls. Will look into this and report back.
