### ISSUE TITLE
Failed to Compile, lodash.throttle

### ISSUE THREAD

**Issue by zplotnikova** [AirLabsTeam/react-drag-to-select#2]
Keep getting when I include the 

`Failed to compile.

./node_modules/react-drag-to-select/dist/index.js
Module not found: Can't resolve 'lodash.throttle' in '...\node_modules\react-drag-to-select\dist'`

when I just add the import `import { useSelectionContainer } from 'react-drag-to-select';`

Any tips on how to resolve?

**Comment by moises-marquez** [comment]
You need to install `lodash.throttle`: https://www.npmjs.com/package/lodash.throttle

**Comment by dwilt** [comment]
@zplotnikova please let us know if this didn't work for you. Closing.
