### ISSUE TITLE
Text cannot be selected ever again, wrong property is removed from body

### ISSUE THREAD

**Issue by uffou** [AirLabsTeam/react-drag-to-select#28]
1. You need to use "user-select" not "userSelect"

https://github.com/AirLabsTeam/react-drag-to-select/blob/0210c96aacd8fe6baeacf8d229e635cb020f89f7/src/hooks/useSelectionLogic.ts#L162

**Comment by uffou** [comment]
and `-webkit-user-select` for safari

**Comment by tomaszczura** [comment]
You are right - will be fixed soon. Thanks!
