### ISSUE TITLE
Remove `NewSelectionBox` from logs

### ISSUE THREAD

**Issue by moises-marquez** [AirLabsTeam/react-drag-to-select#3]
Currently, the console gets polluted with lots of logs for `NewSelectionBox`. Could you remove this log or remove when the `NODE_ENV` environment variable is set to `production`?

I can create a PR with the change if you want.

**Comment by tomaszczura** [comment]
Which version do you use?

**Comment by moises-marquez** [comment]
I'm using version 1.0.3-rc01.

**Comment by tomaszczura** [comment]
It's still in testing stage - could you use 1.0.2?

**Comment by moises-marquez** [comment]
Sure! I will give it a try :)

**Comment by iBasit** [comment]
When installing by yarn or npm, it auto select 1.0.3 and with log. Maybe stage version shouldn't be picked automatically by npm tags, maybe it should be kept on separate branch.
