### ISSUE TITLE
onSelectionEnd is called without onSelectionStart or onSelectionChange first

### ISSUE THREAD

**Issue by mramirezd** [AirLabsTeam/react-drag-to-select#35]
I noticed that when we just click without dragging, the onSelectionEnd event is fired without the onSelection Start being fired first. This is consistent with your documentation but I wonder why this is like this, since I had to add extra logic to work around this.

Also I would like to know if it's possible to send the React.MouseEvent to the onSelectionEnd (or maybe to all of the selection callbacks). For me it would be extremely useful since it would allow me to easily get the ctrl and shift key states as well as handle both the drag and select and the single click selection (with the correct mouse position) with this library.

**Comment by egreen0** [comment]
I'm running into both of the exact same issues

**Comment by dwilt** [comment]
@mramirezd could you put together a codesandbox repro'ing this?

**Comment by mramirezd** [comment]
@dwilt you can easily see what we are talking about by just clicking on the SelectableArea and looking at the logs on this CodeSandBox that I forked from yours: https://codesandbox.io/s/eager-brahmagupta-vjg72m?file=/src/App.tsx.

**Comment by dwilt** [comment]
> @dwilt you can easily see what we are talking about by just clicking on the SelectableArea and looking at the logs on this CodeSandBox that I forked from yours: https://codesandbox.io/s/eager-brahmagupta-vjg72m?file=/src/App.tsx.

Yes, I see what you mean. Just clicking in our codes sandbox demo I see the console logs. I'm going to put up a PR for both these fixes this weekend. cc @tomaszczura

**Comment by mramirezd** [comment]
@dwilt from what I see on the PR now we won't have onSelectionEnd on a single click, which some devs might be already relying on. What I would suggest in order to bring more versatility to this library is to call onSelectionStart on mousedown, onSelectionChange when moving the mouse after the start and onSelectionEnd on mouseup. This would mean that I can use the same callbacks for drag to select and click to select. Also I think that adding a second argument to onSelectionChange with React.MouseEvent could be interesting in some use cases. What do you think about these suggestions?
