### ISSUE TITLE
onSelectionChange gets MouseEvent of the starting click

### ISSUE THREAD

**Issue by PhatNguyen213** [AirLabsTeam/react-drag-to-select#4]
Currently the `onSelectionChange` only receives one parameter which is the selection box.

However while selecting I need to do some calculations based on the `clientX` and `clientY` of the starting click. The starting click may not always be the top left as you can drag from bottom to top, for example.

Is there any ways I can get this information?

**Comment by moises-marquez** [comment]
The selection box is comprised of top, left, width and height. Based on them you should be able to calculate the starting click coordinates (i.e, left - width if your element is on the right side of the horizontal plane).

**Comment by dwilt** [comment]
@PhatNguyen213 going to close this per @moises-marquez's comment as that should suffice for your needs.
