### ISSUE TITLE
Help Required: Example of selecting only when a key (shift) is being pressed

### ISSUE THREAD

**Issue by ndtreviv** [AirLabsTeam/react-drag-to-select#45]
I'd like to only drag-to-select if the user is holding down the shift key. 
Is that possible? Do you have an example for how to do that?

I'm assuming I can just track when shift is being held down and set `isEnabled` to be on `useSelectionContainer` accordingly. Is it sensitive to such changes?

Thanks for your help!

**Comment by tomaszczura** [comment]
Yes, that should work

**Comment by ndtreviv** [comment]
Thanks!
