### ISSUE TITLE
Why is the rect argument needed in the getPointFromEvent function?

### ISSUE THREAD

**Issue by billy5982** [AirLabsTeam/react-drag-to-select#48]
In all cases where the getPointFromEvent function is used, rect is passed as getParentBoundingClientRect(). Is there any specific reason for explicitly providing rect as an argument when it's always the same value?

https://github.com/AirLabsTeam/react-drag-to-select/blob/7ae9ada562d4ebfa288a0079929dd0993b97e2ff/src/hooks/useSelectionLogic.ts#L98

**Comment by tomaszczura** [comment]
It doesn't have to be the same - what if container was resized?

**Comment by billy5982** [comment]
Oh, I wasn't aware of that!
My mistake! Thank you for your accurate and kind reply! I was able to think again. Thank you!

**Comment by billy5982** [comment]
@tomaszczura  I'm so sorry. Can I ask you one more question because there's something I don't understand??
Is it different from declaring and using 'rect = containerRef.current?.getParentBoundingClientRect();' instead of 'rect' factor in 'getPointFromEvent' function?

**Comment by tomaszczura** [comment]
That's a good question. Now I see that `getPointFromEvent ` is called with `rect` param only in one place, and `containerRef.current?.getParentBoundingClientRect();` is passed there. So this param could be removed, since it is not really used

**Comment by billy5982** [comment]
Thank you so much for the good response! Can I register 'pr' for that? @tomaszczura

**Comment by tomaszczura** [comment]
Sure, each help is appreciated ;)

**Comment by billy5982** [comment]
@tomaszczura Thank you so much for your kind reply and confirmation.
