### ISSUE TITLE
Selection box disappears when user stops moving if updating state

### ISSUE THREAD

**Issue by david-bishop-levelstudio** [AirLabsTeam/react-drag-to-select#8]
I'm trying to send the Box object to local state for use elsewhere, but when I do this, the selection box is a little buggy. It disappears when I stop dragging for an instant: 

```
({posSet, canDrawBox, canDrawBoxSet }: SelectionOverlayProps) => {
  
  const handleDrag = useCallback((box: Box) => {
    posSet(box)
  }, [])

  const { DragSelection } = useSelectionContainer({
    onSelectionChange: handleDrag,
    onSelectionEnd: () => canDrawBoxSet(false)
  });

  return (
    <div
      style={{
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        pointerEvents: canDrawBox ? "all" : "none"
      }}>
      <DragSelection />
    </div>
  );
}
```

If I replace posSet() with console.log() it all runs smoothly. Any ideas?

**Comment by Attiley** [comment]
Please use useCallback hook instead of inline function to avoid rerendering
Correct Example: 
const handleSelectionEnd = useCallback(() => { doSomethingHere()},[])
<DragSelection onSelectionEnd={handleSelectionEnd} onSelectionChange={...}/>
Incorrect Example:
<DragSelection onSelectionEnd={() => { doSomethingHere() }} onSelectionChange={...}/>

**Comment by chandlervdw** [comment]
I'm implementing `useCallback` for all of of the passed functions but I'm noticing that `React.memo` is being used for the `DragSelection` component in your example.

I've got the correct elements selecting when they should be but the selection box disappears immediately. If I try to manipulate state (updating the selected items) at all within `onSelectionChange`, I never see it. If I don't, it’s visible the whole time.

**Comment by dwilt** [comment]
@david-bishop-levelstudio can you please create a codesandbox showing the issue you're seeing?

**Comment by androso** [comment]
@dwilt I think the issue can be seen here https://codesandbox.io/s/billowing-lake-rzhid4 the selection box disappears after you've stopped moving the mouse

**Comment by dwilt** [comment]
@androso thanks for pointing out. The issue was is that when you would have a parent re-render because of the internal state change, a brand new `DragSelection` component was being created. Memoizing it fixes the issue as @Attiley pointed out.
