### ISSUE TITLE
Doesn't work if browser window resized

### ISSUE THREAD

**Issue by nickgermaine** [AirLabsTeam/react-drag-to-select#9]
It seems it gets size of selection area at first initialization.  But if I resize my browser window, it seems to select items based on if they were within the new selection size prior to the window resize.

**Comment by dwilt** [comment]
@nickgermaine can you please provide a codesandbox example of this?

**Comment by dwilt** [comment]
@nickgermaine I believe this is the same as https://github.com/AirLabsTeam/react-drag-to-select/issues/12. Will look into fixing this and will report back.

**Comment by dwilt** [comment]
Closing this because I believe this is solved by explaining https://github.com/AirLabsTeam/react-drag-to-select/#scrolling
